version: '2'

services:
  # express server node
  web:
    build: ./containers/expressnode
    expose:
        - 80
    ports:
        - "80:80"
    environment:
        PORT: 80
        HOST: 0.0.0.0
