version: '2'

services:
    expressnode:
        build: .
        stdin_open: true
        tty: true
        expose:
            - 80
        ports:
            - "80:80"
        environment:
            CHAINNAME: ExperimentalChain
            NETWORK_PORT: 80
            RPC_NODE: masternode
            RPC_PORT: 8002
            RPC_USER: multichain-experiments-rpc
            RPC_PASSWORD: QzC3+n2pJR
