version: '2'

services:
    # basenode:
    #     build: kunstmaan/base-multichain
    #     stdin_open: true
    #     tty: true
    masternode:
        build: kunstmaan/master-multichain
        stdin_open: true
        tty: true
        expose:
            - 7557
            - 8002
        environment:
            CHAINNAME: ExperimentalChain
            NETWORK_PORT: 7557
            RPC_PORT: 8002
            RPC_USER: multichain-experiments-rpc
            RPC_PASSWORD: QzC3+n2pJR
            RPC_ALLOW_IP: 0.0.0.0/0.0.0.0
            PARAM_TARGET_BLOCK_SIZE: target-block-time|30
            PARAM_ANYONE_CAN_CONNECT: anyone-can-connect|true
            PARAM_ANYONE_CAN_MINE: anyone-can-mine|true
    slavenode:
        build: kunstmaan/node-multichain
        stdin_open: true
        tty: true
        expose:
            - 7557
            - 8002
        ports:
            - "8002:8002"
        environment:
            CHAINNAME: MyChain
            NETWORK_PORT: 7557
            RPC_PORT: 8002
            RPC_USER: multichain-experiments-rpc
            RPC_PASSWORD: QzC3+n2pJR
            RPC_ALLOW_IP: 0.0.0.0/0.0.0.0
            MASTER_NODE: masternode
        links:
            - masternode
        depends_on:
            - masternode
    explorernode:
        build: kunstmaan/explorer-multichain
        stdin_open: true
        tty: true
        expose:
            - 2750
            - 7557
            - 8002
        ports:
            - "2750:2750"
        environment:
            CHAINNAME: MyChain
            NETWORK_PORT: 7557
            RPC_PORT: 8002
            RPC_USER: multichain-experiments-rpc
            RPC_PASSWORD: QzC3+n2pJR
            RPC_ALLOW_IP: 0.0.0.0/0.0.0.0
            MASTER_NODE: masternode
        links:
            - masternode
        depends_on:
            - masternode
    expressnode:
        build: ./containers/expressnode
        stdin_open: true
        tty: true
        expose:
            - 80
        ports:
            - "80:80"
        environment:
            PORT: 80
            HOST: 0.0.0.0
            RPC_USER: multichain-experiments-rpc
            RPC_PASSWORD: QzC3+n2pJR
            MC_NODE: slavenode
        links:
            - slavenode
        depends_on:
            - slavenode
